baseURL = "https://oozh.pages.dev"
title = "圈圈中文"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "圈圈中文"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "欢迎来到眼镜癖的中文世界!" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = ""

    # The name to display in the copyright section in the footer
    copyrightname = "greycat"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    email = "422561659@qq.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.5

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "greycat"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "说明" # An unique identifier for the button
    name = "说明"       # A display name for the button
    url = "/tags/oozh"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "全部标签"
    name = "全部标签"
    url = "/tags/"       # The path can lead to a content folder too.
    weight = 20

  [[menu.main]]
    identifier = "全部文章"
    name = "全部文章"
    url = "/posts/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
