baseurl: "/"
languageCode: "en-us"
title: "oo Arch"
theme: "hugo-xmag"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true
paginate: 30

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Authors
      url: categories/
      weight: 2
    - name: Tags
      url: tags/
      weight: 3
    - name: About
      url: about/
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Greycat](https://wpa.qq.com/msgrd?v=3&uin=422561659&site=qq&menu=yes) 2023"
  github_edit: "https://github.com/Gexi0619/oozh/tree/master/content/"
  summary_length: 300
  text:
    back: "&larr; Back to Home"
    edit: "Edit this page &rarr;"
    truncated: "&hellip;"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
